apiVersion: v1
kind: Namespace
metadata:
  name: luuun-website2
---
apiVersion: v1
kind: Service
metadata:
  name: luuun-website
  namespace: luuun-website2
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: luuun-website
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: luuun-website
  namespace: luuun-website2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: luuun-website
    spec:
      containers:
      - image: zapgo/luuun-website:v0.015
        imagePullPolicy: Always
        name: luuun-website
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: luuun-website
  namespace: luuun-website2
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - luuun.com
    - www.luuun.com
    secretName: luuun-website-tls
  rules:
  - host: luuun.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: luuun-website
          servicePort: 80
  - host: www.luuun.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: luuun-website
          servicePort: 80
